### ISSUE TITLE
Create Allocations Admin

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/deployment-log#10]
[As described on the website](https://1hive.org/docs/contribute/allocations-payroll.html): 
- "An Allocations Admin is responsible for creating the weekly allocations vote and including all nominees each Monday."

We need to create this role so that we can start fulfilling weekly allocations.

Before that though, we need to agree on the [HONEY minting/supply schedule](https://github.com/1Hive/dao/issues/9).

**Comment by yeqbfgxjiq** [comment]
@lkngtn This is currently you right now right? If so, let me know and I'll update that section on the website
- https://1hive.org/docs/contribute/roles-responsibilities.html

**Comment by lkngtn** [comment]
Yup currently this is my responsibility.

**Comment by yeqbfgxjiq** [comment]
Cool. Added it to the website under Roles and Responsibilities in the Contributing section
- https://1hive.org/docs/contribute/roles-responsibilities.html
