### ISSUE TITLE
MVP Mainnet DAO

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/deployment-log#3]
Currently the missing functionality is:
- Redemptions
- Payroll (may need to deploy this to apm ourselves as it is not currently published, apparently it is functional though)
- Rewards (not super urgent in my opinion, but it is easy to install)

Then Autark can ship TPS to mainnet as a "soft launch" for 1Hive :)

**Comment by lkngtn** [comment]
Do we care if Redemptions has a UI for mainnet mvp? Without a UI we would need to provide some documentation on how to actually redeem tokens.

**Comment by yeqbfgxjiq** [comment]
I think a UI is really important. Is it possible to package and ship it to the Aragon app store just on Rinkeby until we get it audited/tested?
